version: "3.7"
services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    expose:
      - 5432
    networks:
      - backend-database

  auth-service:
    build: .
    image: auth-service
    restart: always
    depends_on:
      - postgres
    ports:
      - 8088:8088
    networks:
      - backend-database

networks:
  backend-database:
